apiVersion: novus.legogroup.io/v1alpha1
kind: WebApp
metadata:
  name: first-app
spec:
  ingress:
    subdomain: first-app
  service:
    image:
      repository: ghcr.io/dtu-platform-workshop/dtu-lukaspj/first-app
      tag: 20260919-e59a884

    useSamePortForHealthProbes: true

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
