apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  finalizers:
    # Ensure that all resources are cleaned up if this Application is deleted
    - resources-finalizer.argocd.argoproj.io
spec:
  # This is your runtime name and runtime environment.
  project: lukaspj-dtu
  source:
    # The URL of the public Helm repository
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    # Which branch/tag/commit to deploy from. HEAD is the default branch in the GitHub repository
    targetRevision: 0.41.1
    # The name of the Chart
    chart: opentelemetry-demo
    helm:
      # Put any environment-specific configuration here
      values: |
        opentelemetry-collector:
          config:
            exporters:
              otlp/gcloud:
                endpoint: "novus-opentelemetry-collector.novus-telemetry.svc.cluster.local:4317"
                tls:
                  insecure: true
            service:
              pipelines:
                traces:
                  exporters: [otlp/gcloud, debug, spanmetrics]
                metrics:
                  exporters: [otlp/gcloud, debug]
                logs:
                  exporters: [otlp/gcloud, debug]
        jaeger:
          enabled: false
        
        prometheus:
          enabled: false
        
        grafana:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    # This should be set to the same as project, i.e. runtime name and runtime environment
    namespace: lukaspj-dtu
  # Sync policy, this should always be set to automated self-heal and prune
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
