apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-warehouse
  finalizers:
    # Ensure that all resources are cleaned up if this Application is deleted
    - resources-finalizer.argocd.argoproj.io
spec:
  # This is your runtime name and runtime environment.
  project: lukaspj-dtu
  source:
    # The URL of the public Helm repository
    repoURL: git@github.com:LEGO/novus-dtu-workshop.git
    # Which branch/tag/commit to deploy from. HEAD is the default branch in the GitHub repository
    targetRevision: HEAD
    # The name of the Chart
    path: remote-warehouse/charts/remote-warehouse
    helm:
      # Put any environment-specific configuration here
      values: |
        image:
          repository: artifactory.novus.legogroup.io/ghcr/lego/novus-dtu-workshop/otel-demo-1
          tag: 20260917-67ba901
        imagePullSecrets:
          - name: novus-pull-secret
        otlpEndpoint: http://novus-opentelemetry-collector.novus-telemetry.svc.cluster.local:4317

  destination:
    server: https://kubernetes.default.svc
    # This should be set to the same as project, i.e. runtime name and runtime environment
    namespace: lukaspj-dtu
  # Sync policy, this should always be set to automated self-heal and prune
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
