apiVersion: novus.legogroup.io/v1alpha1
kind: Service
metadata:
  name: warehouse
spec:
  image:
    repository: ghcr.io/lego/novus-dtu-workshop/simple-remote-warehouse
    tag: 20260919-8acc834

  useSamePortForHealthProbes: true

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
